Question
========

NOTE: BAD QUESTION. We can assign new value labels with val_label() and val_labels(), the syntax is just super
confusing.

Consider the following tibble. Which of the following expressions will remove the value labels from the `hair_color`
column?

```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(labelled)

tmp <- haven::read_spss("data/starwars.sav") |> 
  select(-c(homeworld, species, sex, gender))
```

Answerlist
----------

* `starwars$hair_color <- unlabelled(starwars$hair_color)`
* `unlabelled(starwars$hair_color)`
* `val_label(starwars)$hair_color <- NULL`
* `val_labels(starwars)$hair_color <- NULL`
* `var_labels(starwars)$hair_color <- NULL`
* `val_labels(starwars$hair_color) <- NULL`
* `unlabelled(starwars)$hair_color`
* `starwars$hair_color <- unlabelled(starwars)`
* `starwars <- unlabelled(starwars$hair_color)`

Solution
========

We first need to create an unlabelled version of the `hair_color` vector using `unlabelled(starwars$hair_color)`. Then
we need to overwrite the original `starwars$hair_color` column with our new version.

Answerlist
----------
* Correct
* Wrong: We do not want to remove all the labels
* Wrong: `val_label()` is used to access the value labels for a variable, not to set those labels
* Wrong: `val_labels()` is used to access the value labels, not to set labels
* Wrong: `var_labels()` is used to get the list of variable labels, not to set labels
* Wrong: `val_labels()` is used to get the list of value label, not to set labels
* Wrong: This expression simply prints the `hair_color` vector from an entirely unlabeld version of `starwars`.
* Wrong: This expression overwrites the `hair_color` column with the whole unlabeled data frame.
* Wrong: This expression overwrites the entire data frame with the unlabelled `hair_color` vector.

Meta-information
================
exname: Label SPSS
extype: schoice
exsolution: 100000000
exshuffle: 5
